### ISSUE TITLE
enable \n in vertex labels

### ISSUE THREAD

**Issue by mjrmason** [USCCANA/netplot#11]
Fantastic Package! Vertex labels with new lines are enabled in igraph plotting but not in this package. It would increase my use greatly if I could include new lines in my vertex labels like "Com 12\nMemmory T cells". Maybe a bug, maybe a enhancement... not sure.

**Comment by gvegayon** [comment]
Thank you, @mjrmason! That sounds like a great idea. I'll add it to the to-do list. That said, PRs are more than welcome :).

**Comment by gvegayon** [comment]
Ultimately, the functionality was always there. The issue is the `fontfamily`. Hershey's fonts, for some reason, don't like line breaks. Changing `vertex.label.fontfamily` to `sans` does the trick. I'm closing this now.
