### ISSUE TITLE
remove arrows from edges for undirected graphs

### ISSUE THREAD

**Issue by pkr2103** [USCCANA/netplot#4]
Hi,

Thank you so much for building an incredible network visualization tool! I'm curious if I am missing something. I have an undirected network that I'd like to visualize without edge arrows. I have set skip.arrows=T, but the network plot still shows edge arrows. Is there a straightforward way to remove the arrows that I am missing? 

I am sorry if I am overlooking something obvious.

Thank you so much.

**Comment by gvegayon** [comment]
A bit of a delay, but skip now works as expected ;)
